name: Build and Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Print Node and NPM version
        run: |
          node --version
          npm --version
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build and test
        run: |
          npm run build --if-present
          npm test --if-present
