name: Test Node.js Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Test database connection
        run: |
          node -e "
          const mysql = require('mysql2');
          const connection = mysql.createConnection({
            host: '${{ secrets.DB_HOST }}',
            user: '${{ secrets.DB_USER }}',
            password: '${{ secrets.DB_PASSWORD }}',
            database: '${{ secrets.DB_NAME }}'
          });
          connection.connect(function(err) {
            if (err) {
              console.error('Error connecting to database:', err);
              process.exit(1);
            }
            console.log('Successfully connected to database');
            connection.end();
          });"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
