name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          cp -r ./Client/* .
          rm -rf ./Client
          touch .nojekyll
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
